### ISSUE TITLE
Add toggle button

### ISSUE THREAD

**Issue by jzha411** [UoaWDCC/st-marks#4]
- [ ] Button does not need to be interactive, ie it does not have to change the page colour, it just needs to be there

**Comment by klam656** [comment]
import React from "react";
import { Box, IconButton, Tooltip } from "@mui/material";
import { useTheme } from "@mui/material/styles";
import FormControlLabel from '@mui/material/FormControlLabel';
import Switch from '@mui/material/Switch';
import {
  Home as HomeIcon,
  MenuBook as MenuBookIcon,
} from "@mui/icons-material";
import { Link } from "react-router-dom";
import styles from "./NavBar.module.css";

interface NavBarProps {
  contrast?: boolean;
}

const NavBar: React.FC<NavBarProps> = ({ contrast = false }: NavBarProps) => {
  const theme = useTheme();
  const [darkMode, setMode] = React.useState(false);
  const color = contrast
    ? theme.palette.primary.contrastText
    : theme.palette.primary.main;

  return (
    <Box className={styles.topBarIcons}>
      <Tooltip title="Directory" placement="right">
        <IconButton
          component={Link}
          to="/directory"
          data-testid="directory-button"
          className={styles.clickable}
          size="large"
        >
          <MenuBookIcon htmlColor={color} fontSize="large" />
        </IconButton>
      </Tooltip>
      <Tooltip title="Home" placement="bottom">
        <IconButton
          component={Link}
          to="/"
          data-testid="home-button"
          className={styles.clickable}
          size="large"
        >
          <HomeIcon htmlColor={color} fontSize="large" />
        </IconButton>
      </Tooltip>
      <FormControlLabel
        sx={{
          display: 'block',
        }}
        control={
          <Switch
            checked={darkMode}
            onChange={() => setMode(!darkMode)}
            name="darkMode"
            color="primary"
          />
        }
        label="label"
      />
    </Box>
  );
};

export default NavBar;
